# Sets maximum JVM heap size to 4GB for Gradle and using UTF-8 file encoding
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Enables configuration cache to reuse build configuration phase and improve build speed
org.gradle.configuration-cache=true

# Using official Kotlin coding style guidelines for code formatting
kotlin.code.style=official